services:
  - type: web
    name: diet-plan
    runtime: python
    plan: free
    region: oregon
    buildCommand: "./build.sh"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: MONGO_URI
        sync: false
      - key: DB_NAME
        value: dietplan
      - key: GROQ_API_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: APP_URL
        sync: false
